name: "Weekly Refactor Issue"
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create weekly refactor issue from file
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Weekly Refactor - ${{ github.run_id }}"
          labels: refactor, recurring
          assignees: Jin-HoMLee
          content-filepath: .github/ISSUE_TEMPLATE/weekly-refactor.md
